spring.application.name=discovery-server

# Run on the standard Eureka port
server.port=8761

# Tell Eureka NOT to register itself with another Eureka Server
eureka.client.register-with-eureka=false

# Tell Eureka NOT to fetch the registry from another server (since it is the primary server)
eureka.client.fetch-registry=false

# Set the default zone for this server
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

spring.output.ansi.enabled=always
